### PR TITLE
Indian Flag in CSS

### PR DESCRIPTION
**Pull request by dazzlerkumar**
Please give hacktoberfest labels. Thank You for giving this opportunity.

### CODE REVIEW

**Comment by ismeet010** [comment]
Hi @dazzlerkumar not able to view, can you update the html file(add html, head and body tags)

**Comment by dazzlerkumar** [comment]
Okay! sure.

**Comment by dazzlerkumar** [comment]
@ismeet010 Made the changes.

**Comment by ismeet010** [comment]
Nice work!! :)

**Pull request merged**
