### PR TITLE
added new page with hover animations

### PR DESCRIPTION
**Pull request by cristian-sbardelotto**
I added a new page with button hover animations. It's simple but very nice.

### CODE REVIEW

**Comment by ismeet010** [comment]
Hi @cristian-sbardelotto, can you please update the position of reset button, it is overlapping the color button.
image

**Comment by cristian-sbardelotto** [comment]
Sure, I'll do it right now!

Em dom., 16 de out. de 2022 às 11:43, Ismeet Kour Chhabda <
***@***.***> escreveu:

**Comment by cristian-sbardelotto** [comment]
This button was created on a big monitor, but on my laptop, the error also
happens.


Em dom., 16 de out. de 2022 às 13:37, Cristian Keiber Sbardelotto <
***@***.***> escreveu:

**Comment by cristian-sbardelotto** [comment]
I made the commit. Do you see it?

Em dom., 16 de out. de 2022 às 13:40, Cristian Keiber Sbardelotto <
***@***.***> escreveu:

**Comment by ismeet010** [comment]
It is perfect now :)

**Pull request merged**
